version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      # Updates to maven packages every weekday
      interval: "daily"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Updates to GitHub Actions every weekday
      interval: "daily"
